### PR TITLE
Minor cleanup, use for_each, remove redundant mut

### PR DESCRIPTION
**Pull request by timvisee**
Use cleaner `for_each` function on the range new in [Rust 1.21](https://blog.rust-lang.org/2017/10/12/Rust-1.21.html).
Remove redundant and unnecessary mutable references.
Simplify if-statement.

### CODE REVIEW

**Comment by alexanderbez** [comment]
Hey @timvisee! Thanks for the contribution. I haven't really used Rust since this example. Changes look great however! Mind adding a few unit tests as well?

**Comment by timvisee** [comment]
@alexanderbez Sure, I'll take a look into unit tests as soon as I've time.
Tests should be quite simple with this snippet.

**Comment by alexanderbez** [comment]
Thanks @timvisee!

**Comment by timvisee** [comment]
Hello @alexanderbez 

Sorry for the late update. I totally forgot about it, and found this pull request in my personal log.
Anyhow, I've added unit tests as you've requested.

Notable changes:
- Updated comment and indent style as per Rust convention.
- Renamed `merge_sort.rs` to `lib.rs`, to make Rust recognize it as library to make it runnable (for testing) without additional configuration.
- Fixed a minor sorting issue in my previous commit :-)
- Added many unit test as requested, with all the situations I could think of. I put these tests in a `tests` module, to better separate it from the merge logic.
- Moved the example to make it runnable using `cargo run --example sort`.
- Updated the README to reflect these changes.

These tests can now be run using `cargo test`.

Unit test results
[Unit test results (screenshot)](https://u.visee.me/Selection-3e381936.png)

I hope you're still able to accept it, haha.

**Comment by alexanderbez** [comment]
Good work @timvisee. Thanks for the changes 👍

**Pull request merged**
